# Pre Process The Database

In [358]:
import pandas as pd
import numpy as np
import random

In [359]:
#create df
df = pd.read_csv('nbaDatabase2004-2024.csv')
df.head()

,date,homeTeam,homeTeam_id,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,homeTeam_points_q4,homeTeam_points_1OT,homeTeam_points_2OT,...,awayTeam_3P,awayTeam_O_Reb,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner
0,"June 17, 2024",Boston Celtics,BOS,106,28,39,19,20,0,0,...,11-37,7,28,35,18,4,4,13,20,Boston Celtics
1,"June 14, 2024",Dallas Mavericks,DAL,122,34,27,31,30,0,0,...,14-41,4,27,31,18,2,5,13,19,Dallas Mavericks
2,"June 12, 2024",Dallas Mavericks,DAL,99,31,20,19,29,0,0,...,17-46,6,30,36,26,4,6,9,19,Boston Celtics
3,"June 09, 2024",Boston Celtics,BOS,105,25,29,29,22,0,0,...,6-26,9,34,43,21,5,3,15,17,Boston Celtics
4,"June 06, 2024",Boston Celtics,BOS,107,37,26,23,21,0,0,...,7-27,10,33,43,9,8,1,11,16,Boston Celtics

In [360]:
df['date'] = pd.to_datetime(df['date'])
df

,date,homeTeam,homeTeam_id,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,homeTeam_points_q4,homeTeam_points_1OT,homeTeam_points_2OT,...,awayTeam_3P,awayTeam_O_Reb,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner
0,2024-06-17,Boston Celtics,BOS,106,28,39,19,20,0,0,...,11-37,7,28,35,18,4,4,13,20,Boston Celtics
1,2024-06-14,Dallas Mavericks,DAL,122,34,27,31,30,0,0,...,14-41,4,27,31,18,2,5,13,19,Dallas Mavericks
2,2024-06-12,Dallas Mavericks,DAL,99,31,20,19,29,0,0,...,17-46,6,30,36,26,4,6,9,19,Boston Celtics
3,2024-06-09,Boston Celtics,BOS,105,25,29,29,22,0,0,...,6-26,9,34,43,21,5,3,15,17,Boston Celtics
4,2024-06-06,Boston Celtics,BOS,107,37,26,23,21,0,0,...,7-27,10,33,43,9,8,1,11,16,Boston Celtics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2004-11-03,Cleveland Cavaliers,CLE,104,21,19,27,18,9,10,...,4-17,11,36,47,24,9,5,13,28,Indiana Pacers
25727,2004-11-03,Boston Celtics,BOS,95,22,31,30,12,0,0,...,9-24,14,27,41,20,9,2,16,26,Philadelphia 76ers
25728,2004-11-02,Los Angeles Lakers,LAL,89,24,26,22,17,0,0,...,3-12,16,32,48,17,10,8,16,21,Los Angeles Lakers
25729,2004-11-02,Detroit Pistons,DET,87,19,18,22,28,0,0,...,6-13,9,27,36,8,4,5,16,24,Detroit Pistons
25730,2004-11-02,Dallas Mavericks,DAL,107,30,24,25,28,0,0,...,3-17,18,25,43,21,9,6,15,19,Dallas Mavericks

In [361]:
def get_season(date):
    year = date.year
    #NBA season starts in October
    if date.month >= 10:
        return f'{year}-{year+1}'
    else:
        return f'{year-1}-{year}'

#initalize season column
df['season'] = df['date'].apply(get_season)

df

,date,homeTeam,homeTeam_id,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,homeTeam_points_q4,homeTeam_points_1OT,homeTeam_points_2OT,...,awayTeam_O_Reb,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season
0,2024-06-17,Boston Celtics,BOS,106,28,39,19,20,0,0,...,7,28,35,18,4,4,13,20,Boston Celtics,2023-2024
1,2024-06-14,Dallas Mavericks,DAL,122,34,27,31,30,0,0,...,4,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024
2,2024-06-12,Dallas Mavericks,DAL,99,31,20,19,29,0,0,...,6,30,36,26,4,6,9,19,Boston Celtics,2023-2024
3,2024-06-09,Boston Celtics,BOS,105,25,29,29,22,0,0,...,9,34,43,21,5,3,15,17,Boston Celtics,2023-2024
4,2024-06-06,Boston Celtics,BOS,107,37,26,23,21,0,0,...,10,33,43,9,8,1,11,16,Boston Celtics,2023-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2004-11-03,Cleveland Cavaliers,CLE,104,21,19,27,18,9,10,...,11,36,47,24,9,5,13,28,Indiana Pacers,2004-2005
25727,2004-11-03,Boston Celtics,BOS,95,22,31,30,12,0,0,...,14,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005
25728,2004-11-02,Los Angeles Lakers,LAL,89,24,26,22,17,0,0,...,16,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005
25729,2004-11-02,Detroit Pistons,DET,87,19,18,22,28,0,0,...,9,27,36,8,4,5,16,24,Detroit Pistons,2004-2005
25730,2004-11-02,Dallas Mavericks,DAL,107,30,24,25,28,0,0,...,18,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005

In [362]:
#initalize the new columns at appropriate index
df['homeTeam_wins'] = 0
df['homeTeam_losses'] = 0
df['awayTeam_wins'] = 0
df['awayTeam_losses'] = 0
cols = df.columns.tolist()
cols.insert(cols.index('homeTeam_id')+1, cols.pop(cols.index('homeTeam_wins')))
cols.insert(cols.index('homeTeam_wins')+1, cols.pop(cols.index('homeTeam_losses')))
cols.insert(cols.index('awayTeam_id')+1, cols.pop(cols.index('awayTeam_wins')))
cols.insert(cols.index('awayTeam_wins')+1, cols.pop(cols.index('awayTeam_losses')))

df = df[cols]
df

,date,homeTeam,homeTeam_id,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,homeTeam_points_q4,...,awayTeam_O_Reb,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season
0,2024-06-17,Boston Celtics,BOS,0,0,106,28,39,19,20,...,7,28,35,18,4,4,13,20,Boston Celtics,2023-2024
1,2024-06-14,Dallas Mavericks,DAL,0,0,122,34,27,31,30,...,4,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024
2,2024-06-12,Dallas Mavericks,DAL,0,0,99,31,20,19,29,...,6,30,36,26,4,6,9,19,Boston Celtics,2023-2024
3,2024-06-09,Boston Celtics,BOS,0,0,105,25,29,29,22,...,9,34,43,21,5,3,15,17,Boston Celtics,2023-2024
4,2024-06-06,Boston Celtics,BOS,0,0,107,37,26,23,21,...,10,33,43,9,8,1,11,16,Boston Celtics,2023-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2004-11-03,Cleveland Cavaliers,CLE,0,0,104,21,19,27,18,...,11,36,47,24,9,5,13,28,Indiana Pacers,2004-2005
25727,2004-11-03,Boston Celtics,BOS,0,0,95,22,31,30,12,...,14,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005
25728,2004-11-02,Los Angeles Lakers,LAL,0,0,89,24,26,22,17,...,16,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005
25729,2004-11-02,Detroit Pistons,DET,0,0,87,19,18,22,28,...,9,27,36,8,4,5,16,24,Detroit Pistons,2004-2005
25730,2004-11-02,Dallas Mavericks,DAL,0,0,107,30,24,25,28,...,18,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005

In [363]:
print(df.columns)

Index(['date', 'homeTeam', 'homeTeam_id', 'homeTeam_wins', 'homeTeam_losses',
       'homeTeam_points_total', 'homeTeam_points_q1', 'homeTeam_points_q2',
       'homeTeam_points_q3', 'homeTeam_points_q4', 'homeTeam_points_1OT',
       'homeTeam_points_2OT', 'homeTeam_points_3OT', 'homeTeam_points_4OT',
       'homeTeam_FG', 'homeTeam_3P', 'homeTeam_O_Reb', 'homeTeam_D_Reb',
       'homeTeam_Total_Reb', 'homeTeam_Ast', 'homeTeam_Stl', 'homeTeam_Blk',
       'homeTeam_TO', 'homeTeam_PF', 'awayTeam', 'awayTeam_id',
       'awayTeam_wins', 'awayTeam_losses', 'awayTeam_points_total',
       'awayTeam_points_q1', 'awayTeam_points_q2', 'awayTeam_points_q3',
       'awayTeam_points_q4', 'awayTeam_points_1OT', 'awayTeam_points_2OT',
       'awayTeam_points_3OT', 'awayTeam_points_4OT', 'awayTeam_FG',
       'awayTeam_3P', 'awayTeam_O_Reb', 'awayTeam_D_Reb', 'awayTeam_Total_Reb',
       'awayTeam_Ast', 'awayTeam_Stl', 'awayTeam_Blk', 'awayTeam_TO',
       'awayTeam_PF', 'winner', 'season'],
      dtype='object')

In [364]:
#reverse df
df = df.iloc[::-1].reset_index(drop=True)
df

,date,homeTeam,homeTeam_id,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,homeTeam_points_q4,...,awayTeam_O_Reb,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season
0,2004-11-02,Dallas Mavericks,DAL,0,0,107,30,24,25,28,...,18,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005
1,2004-11-02,Detroit Pistons,DET,0,0,87,19,18,22,28,...,9,27,36,8,4,5,16,24,Detroit Pistons,2004-2005
2,2004-11-02,Los Angeles Lakers,LAL,0,0,89,24,26,22,17,...,16,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005
3,2004-11-03,Boston Celtics,BOS,0,0,95,22,31,30,12,...,14,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005
4,2004-11-03,Cleveland Cavaliers,CLE,0,0,104,21,19,27,18,...,11,36,47,24,9,5,13,28,Indiana Pacers,2004-2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2024-06-06,Boston Celtics,BOS,0,0,107,37,26,23,21,...,10,33,43,9,8,1,11,16,Boston Celtics,2023-2024
25727,2024-06-09,Boston Celtics,BOS,0,0,105,25,29,29,22,...,9,34,43,21,5,3,15,17,Boston Celtics,2023-2024
25728,2024-06-12,Dallas Mavericks,DAL,0,0,99,31,20,19,29,...,6,30,36,26,4,6,9,19,Boston Celtics,2023-2024
25729,2024-06-14,Dallas Mavericks,DAL,0,0,122,34,27,31,30,...,4,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024
25730,2024-06-17,Boston Celtics,BOS,0,0,106,28,39,19,20,...,7,28,35,18,4,4,13,20,Boston Celtics,2023-2024

In [365]:
def extract_win_loss(dfwithSeason):    
    #initalize dictionaries to track wins and losses
    win_count = {}
    loss_count = {}
    for index, row in dfwithSeason.iterrows():
        #get homeTeam, awayTeam, winner, season from row
        homeTeam = row['homeTeam']
        awayTeam = row['awayTeam']
        winner = row['winner']
        season = row['season']
        #initalize win and loss counts for teams
        if homeTeam not in win_count:
            win_count[homeTeam] = 0
            loss_count[homeTeam] = 0
        if awayTeam not in win_count:
            win_count[awayTeam] = 0
            loss_count[awayTeam] = 0
        
        #update win/loss counts based on winner
        if winner == homeTeam:
            win_count[homeTeam] +=1
            loss_count[awayTeam] +=1
        elif winner == awayTeam:
            win_count[awayTeam] +=1
            loss_count[homeTeam] +=1

        #assign current win/loss counts
        #subtract 1 from the input as we want their previous to the game
        dfwithSeason.at[index, 'homeTeam_wins'] = max(win_count[homeTeam]-1, 0)
        dfwithSeason.at[index, 'homeTeam_losses'] = max(loss_count[homeTeam]-1, 0)
        dfwithSeason.at[index, 'awayTeam_wins'] = max(win_count[awayTeam]-1, 0)
        dfwithSeason.at[index, 'awayTeam_losses'] = max(loss_count[awayTeam]-1, 0)
    return dfwithSeason    

df = df.groupby('season', group_keys=False).apply(extract_win_loss)
df

,date,homeTeam,homeTeam_id,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,homeTeam_points_q4,...,awayTeam_O_Reb,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season
0,2004-11-02,Dallas Mavericks,DAL,0,0,107,30,24,25,28,...,18,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005
1,2004-11-02,Detroit Pistons,DET,0,0,87,19,18,22,28,...,9,27,36,8,4,5,16,24,Detroit Pistons,2004-2005
2,2004-11-02,Los Angeles Lakers,LAL,0,0,89,24,26,22,17,...,16,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005
3,2004-11-03,Boston Celtics,BOS,0,0,95,22,31,30,12,...,14,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005
4,2004-11-03,Cleveland Cavaliers,CLE,0,0,104,21,19,27,18,...,11,36,47,24,9,5,13,28,Indiana Pacers,2004-2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2024-06-06,Boston Celtics,BOS,76,19,107,37,26,23,21,...,10,33,43,9,8,1,11,16,Boston Celtics,2023-2024
25727,2024-06-09,Boston Celtics,BOS,77,19,105,25,29,29,22,...,9,34,43,21,5,3,15,17,Boston Celtics,2023-2024
25728,2024-06-12,Dallas Mavericks,DAL,61,39,99,31,20,19,29,...,6,30,36,26,4,6,9,19,Boston Celtics,2023-2024
25729,2024-06-14,Dallas Mavericks,DAL,62,39,122,34,27,31,30,...,4,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024
25730,2024-06-17,Boston Celtics,BOS,79,20,106,28,39,19,20,...,7,28,35,18,4,4,13,20,Boston Celtics,2023-2024

In [366]:
#insert win% column
#if team has zero win then win percentage is zero
#if team has more than zero wins and zero losses win percentage is 100 - divide by zero error handler
df.insert(df.columns.get_loc('homeTeam_id') + 1, 'homeTeam_win%', np.where(df['homeTeam_wins'] == 0, 0, np.where(df['homeTeam_losses'] == 0, 1.0, df['homeTeam_wins'] / (df['homeTeam_wins'] + df['homeTeam_losses']))))
df.insert(df.columns.get_loc('awayTeam_id') + 1, 'awayTeam_win%', np.where(df['awayTeam_wins'] == 0, 0, np.where(df['awayTeam_losses'] == 0, 1.0, df['awayTeam_wins'] / (df['awayTeam_wins'] + df['awayTeam_losses']))))

columns_of_interest = ['homeTeam_win%', 'homeTeam_wins', 'homeTeam_losses', 'awayTeam_win%', 'awayTeam_wins', 'awayTeam_losses']

first_row = df.iloc[0]
row_index = first_row.name 
print(f"Row {row_index + 1}:") 
for column, value in first_row.items():
    if column in columns_of_interest:
        print(f"  Column: {column}, Value: {value}")
    
#confirm this worked as intended
for i in range(2):
    random_row = random.randint(1, len(df.index))
    print(f"Row {random_row}:")
    row = df.iloc[random_row-1]
    for column, value in row.items():
        if column in columns_of_interest:
            print(f"  Column: {column}, Value: {value}")
    print("-" * 30)

Row 1:
  Column: homeTeam_win%, Value: 0.0
  Column: homeTeam_wins, Value: 0
  Column: homeTeam_losses, Value: 0
  Column: awayTeam_win%, Value: 0.0
  Column: awayTeam_wins, Value: 0
  Column: awayTeam_losses, Value: 0
Row 20248:
  Column: homeTeam_win%, Value: 0.7450980392156863
  Column: homeTeam_wins, Value: 38
  Column: homeTeam_losses, Value: 13
  Column: awayTeam_win%, Value: 0.4489795918367347
  Column: awayTeam_wins, Value: 22
  Column: awayTeam_losses, Value: 27
------------------------------
Row 13355:
  Column: homeTeam_win%, Value: 0.8518518518518519
  Column: homeTeam_wins, Value: 23
  Column: homeTeam_losses, Value: 4
  Column: awayTeam_win%, Value: 0.14814814814814814
  Column: awayTeam_wins, Value: 4
  Column: awayTeam_losses, Value: 23
------------------------------

In [367]:
#insert column for 3P made
df.insert(df.columns.get_loc('homeTeam_3P') + 1, 'homeTeam_3P_made', df['homeTeam_3P'].str.split('-').apply(lambda x: int(x[0]) if isinstance(x, list) and len(x) == 2 else np.nan))
df.insert(df.columns.get_loc('awayTeam_3P') + 1, 'awayTeam_3P_made', df['awayTeam_3P'].str.split('-').apply(lambda x: int(x[0]) if isinstance(x, list) and len(x) == 2 else np.nan))

columns_of_interest = ['homeTeam_3P', 'homeTeam_3P_made', 'awayTeam_3P', 'awayTeam_3P_made']

#confirm this worked as intended
first_row = df.iloc[0]
row_index = first_row.name 
print(f"Row {row_index + 1}:") 
for column, value in first_row.items():
    if column in columns_of_interest:
        print(f"  Column: {column}, Value: {value}")
    
for i in range(2):
    random_row = random.randint(1, len(df.index))
    print(f"Row {random_row}:")
    row = df.iloc[random_row-1]
    for column, value in row.items():
        if column in columns_of_interest:
            print(f"  Column: {column}, Value: {value}")
    print("-" * 30)

Row 1:
  Column: homeTeam_3P, Value: 7-16
  Column: homeTeam_3P_made, Value: 7
  Column: awayTeam_3P, Value: 3-17
  Column: awayTeam_3P_made, Value: 3
Row 25047:
  Column: homeTeam_3P, Value: 10-30
  Column: homeTeam_3P_made, Value: 10
  Column: awayTeam_3P, Value: 10-39
  Column: awayTeam_3P_made, Value: 10
------------------------------
Row 21370:
  Column: homeTeam_3P, Value: 13-32
  Column: homeTeam_3P_made, Value: 13
  Column: awayTeam_3P, Value: 13-37
  Column: awayTeam_3P_made, Value: 13
------------------------------

In [368]:
#format 3 pointers as a percentage
df['homeTeam_3P'] = df['homeTeam_3P'].str.split('-').apply(lambda x: int(x[0]) / int(x[1]) if isinstance(x, list) and len(x) == 2 else np.nan)
df['awayTeam_3P'] = df['awayTeam_3P'].str.split('-').apply(lambda x: int(x[0]) / int(x[1]) if isinstance(x, list) and len(x) == 2 else np.nan)

#confirm this worked as intended
first_row = df.iloc[0]
row_index = first_row.name 
print(f"Row {row_index + 1}:") 
for column, value in first_row.items():
    if column in columns_of_interest:
        print(f"  Column: {column}, Value: {value}")
    
for i in range(2):
    random_row = random.randint(1, len(df.index))
    print(f"Row {random_row}:")
    row = df.iloc[random_row-1]
    for column, value in row.items():
        if column in columns_of_interest:
            print(f"  Column: {column}, Value: {value}")
    print("-" * 30)

Row 1:
  Column: homeTeam_3P, Value: 0.4375
  Column: homeTeam_3P_made, Value: 7
  Column: awayTeam_3P, Value: 0.17647058823529413
  Column: awayTeam_3P_made, Value: 3
Row 19612:
  Column: homeTeam_3P, Value: 0.3225806451612903
  Column: homeTeam_3P_made, Value: 10
  Column: awayTeam_3P, Value: 0.45714285714285713
  Column: awayTeam_3P_made, Value: 16
------------------------------
Row 11522:
  Column: homeTeam_3P, Value: 0.26666666666666666
  Column: homeTeam_3P_made, Value: 4
  Column: awayTeam_3P, Value: 0.16
  Column: awayTeam_3P_made, Value: 4
------------------------------

In [369]:
#create column for field goals made
df.insert(df.columns.get_loc('homeTeam_FG') + 1, 'homeTeam_FG_made', df['homeTeam_FG'].str.split('-').apply(lambda x: int(x[0]) if isinstance(x, list) and len(x) == 2 else np.nan))
df.insert(df.columns.get_loc('awayTeam_FG') + 1, 'awayTeam_FG_made', df['awayTeam_FG'].str.split('-').apply(lambda x: int(x[0]) if isinstance(x, list) and len(x) == 2 else np.nan))

columns_of_interest = ['homeTeam_FG', 'homeTeam_FG_made', 'awayTeam_FG', 'awayTeam_FG_made']

#confirm this worked as intended
first_row = df.iloc[0]
row_index = first_row.name 
print(f"Row {row_index + 1}:") 
for column, value in first_row.items():
    if column in columns_of_interest:
        print(f"  Column: {column}, Value: {value}")
    
for i in range(2):
    random_row = random.randint(1, len(df.index))
    print(f"Row {random_row}:")
    row = df.iloc[random_row-1]
    for column, value in row.items():
        if column in columns_of_interest:
            print(f"  Column: {column}, Value: {value}")
    print("-" * 30)

Row 1:
  Column: homeTeam_FG, Value: 40-81
  Column: homeTeam_FG_made, Value: 40
  Column: awayTeam_FG, Value: 36-87
  Column: awayTeam_FG_made, Value: 36
Row 4949:
  Column: homeTeam_FG, Value: 39-79
  Column: homeTeam_FG_made, Value: 39
  Column: awayTeam_FG, Value: 34-78
  Column: awayTeam_FG_made, Value: 34
------------------------------
Row 11412:
  Column: homeTeam_FG, Value: 36-76
  Column: homeTeam_FG_made, Value: 36
  Column: awayTeam_FG, Value: 30-83
  Column: awayTeam_FG_made, Value: 30
------------------------------

In [370]:
#format field goals as a percentage
df['homeTeam_FG'] = df['homeTeam_FG'].str.split('-').apply(lambda x: int(x[0]) / int(x[1]) if isinstance(x, list) and len(x) == 2 else np.nan)
df['awayTeam_FG'] = df['awayTeam_FG'].str.split('-').apply(lambda x: int(x[0]) / int(x[1]) if isinstance(x, list) and len(x) == 2 else np.nan)

#confirm this worked as intended
#confirm this worked as intended
first_row = df.iloc[0]
row_index = first_row.name 
print(f"Row {row_index + 1}:") 
for column, value in first_row.items():
    if column in columns_of_interest:
        print(f"  Column: {column}, Value: {value}")
    
for i in range(2):
    random_row = random.randint(1, len(df.index))
    print(f"Row {random_row}:")
    row = df.iloc[random_row-1]
    for column, value in row.items():
        if column in columns_of_interest:
            print(f"  Column: {column}, Value: {value}")
    print("-" * 30)

Row 1:
  Column: homeTeam_FG, Value: 0.49382716049382713
  Column: homeTeam_FG_made, Value: 40
  Column: awayTeam_FG, Value: 0.41379310344827586
  Column: awayTeam_FG_made, Value: 36
Row 6594:
  Column: homeTeam_FG, Value: 0.3804347826086957
  Column: homeTeam_FG_made, Value: 35
  Column: awayTeam_FG, Value: 0.3877551020408163
  Column: awayTeam_FG_made, Value: 38
------------------------------
Row 13382:
  Column: homeTeam_FG, Value: 0.3411764705882353
  Column: homeTeam_FG_made, Value: 29
  Column: awayTeam_FG, Value: 0.4444444444444444
  Column: awayTeam_FG_made, Value: 40
------------------------------

In [371]:
df['isPlayoffGame'] = False
for index, row in df.iterrows():
    playoff_start_dates = {
        "2004-2005": "2005-04-23",
        "2005-2006": "2006-04-22",
        "2006-2007": "2007-04-21",
        "2007-2008": "2008-04-19",
        "2008-2009": "2009-04-18",
        "2009-2010": "2010-04-17",
        "2010-2011": "2011-04-16",
        "2011-2012": "2012-04-28",
        "2012-2013": "2013-04-20",
        "2013-2014": "2014-04-19",
        "2014-2015": "2015-04-18",
        "2015-2016": "2016-04-16",
        "2016-2017": "2017-04-15",
        "2017-2018": "2018-04-14",
        "2018-2019": "2019-04-13",
        "2019-2020": "2020-08-17",
        "2020-2021": "2021-05-22",
        "2021-2022": "2022-04-16",
        "2022-2023": "2023-04-15",
        "2023-2024": "2024-04-20"
    }
    playoff_end_dates = {
        "2004-2005": "2005-06-23",
        "2005-2006": "2006-06-20",
        "2006-2007": "2007-06-14",
        "2007-2008": "2008-06-17",
        "2008-2009": "2009-06-14",
        "2009-2010": "2010-06-17",
        "2010-2011": "2011-06-12",
        "2011-2012": "2012-06-21",
        "2012-2013": "2013-06-20",
        "2013-2014": "2014-06-15",
        "2014-2015": "2015-06-16",
        "2015-2016": "2016-06-19",
        "2016-2017": "2017-06-12",
        "2017-2018": "2018-06-08",
        "2018-2019": "2019-06-13",
        "2019-2020": "2020-10-11",
        "2020-2021": "2021-07-20",
        "2021-2022": "2022-06-16",
        "2022-2023": "2023-06-12",
        "2023-2024": "2024-06-17"  
    }

    season = row['season']
    date = row['date']
    if date >= pd.to_datetime(playoff_start_dates[season]) and date <= pd.to_datetime(playoff_end_dates[season]):
        df.at[index, 'isPlayoffGame'] = True



df

,date,homeTeam,homeTeam_id,homeTeam_win%,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,...,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season,isPlayoffGame
0,2004-11-02,Dallas Mavericks,DAL,0.000000,0,0,107,30,24,25,...,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005,False
1,2004-11-02,Detroit Pistons,DET,0.000000,0,0,87,19,18,22,...,27,36,8,4,5,16,24,Detroit Pistons,2004-2005,False
2,2004-11-02,Los Angeles Lakers,LAL,0.000000,0,0,89,24,26,22,...,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005,False
3,2004-11-03,Boston Celtics,BOS,0.000000,0,0,95,22,31,30,...,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005,False
4,2004-11-03,Cleveland Cavaliers,CLE,0.000000,0,0,104,21,19,27,...,36,47,24,9,5,13,28,Indiana Pacers,2004-2005,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2024-06-06,Boston Celtics,BOS,0.800000,76,19,107,37,26,23,...,33,43,9,8,1,11,16,Boston Celtics,2023-2024,True
25727,2024-06-09,Boston Celtics,BOS,0.802083,77,19,105,25,29,29,...,34,43,21,5,3,15,17,Boston Celtics,2023-2024,True
25728,2024-06-12,Dallas Mavericks,DAL,0.610000,61,39,99,31,20,19,...,30,36,26,4,6,9,19,Boston Celtics,2023-2024,True
25729,2024-06-14,Dallas Mavericks,DAL,0.613861,62,39,122,34,27,31,...,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024,True
25730,2024-06-17,Boston Celtics,BOS,0.797980,79,20,106,28,39,19,...,28,35,18,4,4,13,20,Boston Celtics,2023-2024,True

In [372]:
#reverse df
df = df.iloc[::-1].reset_index(drop=True)
df

,date,homeTeam,homeTeam_id,homeTeam_win%,homeTeam_wins,homeTeam_losses,homeTeam_points_total,homeTeam_points_q1,homeTeam_points_q2,homeTeam_points_q3,...,awayTeam_D_Reb,awayTeam_Total_Reb,awayTeam_Ast,awayTeam_Stl,awayTeam_Blk,awayTeam_TO,awayTeam_PF,winner,season,isPlayoffGame
0,2024-06-17,Boston Celtics,BOS,0.797980,79,20,106,28,39,19,...,28,35,18,4,4,13,20,Boston Celtics,2023-2024,True
1,2024-06-14,Dallas Mavericks,DAL,0.613861,62,39,122,34,27,31,...,27,31,18,2,5,13,19,Dallas Mavericks,2023-2024,True
2,2024-06-12,Dallas Mavericks,DAL,0.610000,61,39,99,31,20,19,...,30,36,26,4,6,9,19,Boston Celtics,2023-2024,True
3,2024-06-09,Boston Celtics,BOS,0.802083,77,19,105,25,29,29,...,34,43,21,5,3,15,17,Boston Celtics,2023-2024,True
4,2024-06-06,Boston Celtics,BOS,0.800000,76,19,107,37,26,23,...,33,43,9,8,1,11,16,Boston Celtics,2023-2024,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,2004-11-03,Cleveland Cavaliers,CLE,0.000000,0,0,104,21,19,27,...,36,47,24,9,5,13,28,Indiana Pacers,2004-2005,False
25727,2004-11-03,Boston Celtics,BOS,0.000000,0,0,95,22,31,30,...,27,41,20,9,2,16,26,Philadelphia 76ers,2004-2005,False
25728,2004-11-02,Los Angeles Lakers,LAL,0.000000,0,0,89,24,26,22,...,32,48,17,10,8,16,21,Los Angeles Lakers,2004-2005,False
25729,2004-11-02,Detroit Pistons,DET,0.000000,0,0,87,19,18,22,...,27,36,8,4,5,16,24,Detroit Pistons,2004-2005,False
25730,2004-11-02,Dallas Mavericks,DAL,0.000000,0,0,107,30,24,25,...,25,43,21,9,6,15,19,Dallas Mavericks,2004-2005,False

In [373]:
df.to_csv('nbaDatabasePreProcessed2004-2024.csv', index=False)